[workspace]
members = [
    "xtask",
    "core",
    "runtime",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Gregory Wildes"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]

